//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayrollEstimator.Resources.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add dependent.
        /// </summary>
        public static string AddDependent {
            get {
                return ResourceManager.GetString("AddDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Benefits Deduction.
        /// </summary>
        public static string AnnualBenefitsDeduction {
            get {
                return ResourceManager.GetString("AnnualBenefitsDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Net Cost.
        /// </summary>
        public static string AnnualNetCost {
            get {
                return ResourceManager.GetString("AnnualNetCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Pay.
        /// </summary>
        public static string AnnualPay {
            get {
                return ResourceManager.GetString("AnnualPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits Discount.
        /// </summary>
        public static string BenefitsDiscount {
            get {
                return ResourceManager.GetString("BenefitsDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-weekly Benefits Deduction.
        /// </summary>
        public static string BiWeeklyBenefitsDeduction {
            get {
                return ResourceManager.GetString("BiWeeklyBenefitsDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-weekly Net Cost.
        /// </summary>
        public static string BiWeeklyNetCost {
            get {
                return ResourceManager.GetString("BiWeeklyNetCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-weekly Pay.
        /// </summary>
        public static string BiWeeklyPay {
            get {
                return ResourceManager.GetString("BiWeeklyPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and last name are required for all dependents..
        /// </summary>
        public static string DependentNameRequiredError {
            get {
                return ResourceManager.GetString("DependentNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        public static string Dependents {
            get {
                return ResourceManager.GetString("Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents Annual Benefits Deduction.
        /// </summary>
        public static string DependentsAnnualBenefitsDeduction {
            get {
                return ResourceManager.GetString("DependentsAnnualBenefitsDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depedents Bi-weekly Benefits Deduction.
        /// </summary>
        public static string DependentsBiWeeklyBenefitsDeduction {
            get {
                return ResourceManager.GetString("DependentsBiWeeklyBenefitsDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required..
        /// </summary>
        public static string FirstNameRequiredError {
            get {
                return ResourceManager.GetString("FirstNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required..
        /// </summary>
        public static string LastNameRequiredError {
            get {
                return ResourceManager.GetString("LastNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s first and last name are required..
        /// </summary>
        public static string NameRequiredError {
            get {
                return ResourceManager.GetString("NameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Estimator.
        /// </summary>
        public static string PayrollEstimatorTitle {
            get {
                return ResourceManager.GetString("PayrollEstimatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
    }
}
